// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public  class Search55LGTVTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() throws MalformedURLException {
        driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.firefox());
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void search55LGTV() {
        // Test name: Search 55' LG TV
        // Step # | name | target | value
        // 1 | open | https://www.bestbuy.com/ |
        driver.get("https://www.bestbuy.com/");
        // 2 | click | id=gh-search-input |
        driver.findElement(By.id("gh-search-input")).click();
        // 3 | type | id=gh-search-input | lg smart tv
        driver.findElement(By.id("gh-search-input")).sendKeys("lg smart tv");
        // 4 | click | css=.header-search-icon > .w-300 |
        driver.findElement(By.cssSelector(".header-search-icon > .w-300")).click();
        // 6 | click | xpath=//img[@alt='LG - 65” Class UT70 Series LED 4K UHD Smart webOS TV (2024) - Front_Zoom'] |
        driver.findElement(By.xpath("//img[@alt=\'LG - 65” Class UT70 Series LED 4K UHD Smart webOS TV (2024) - Front_Zoom\']")).click();
        // 7 | runScript | window.scrollTo(0,13) |
        js.executeScript("window.scrollTo(0,13)");
        // 8 | mouseOver | css=.heading-4 |
        {
            WebElement element = driver.findElement(By.cssSelector(".heading-4"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 9 | mouseOver | css=.shadow-none > .m-none |
        {
            WebElement element = driver.findElement(By.cssSelector(".shadow-none > .m-none"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 10 | mouseOut | css=.shadow-none > .m-none |
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        // 11 | assertElementPresent | css=.priceView-hero-price > span:nth-child(1) |
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".priceView-hero-price > span:nth-child(1)"));
            assert(elements.size() > 0);
        }
    }
}
